const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding comprehensive quest data...')

  // ============================================
  // BADGES
  // ============================================
  console.log('Creating badges...')
  
  const badges = await Promise.all([
    // Progress badges
    prisma.badge.upsert({
      where: { slug: 'first-steps' },
      update: {},
      create: {
        slug: 'first-steps',
        name: 'First Steps',
        description: 'Complete your first quest',
        icon: 'footprints',
        color: '#22c55e',
        type: 'PROGRESS',
        rarity: 'COMMON',
        criteria: { type: 'quest_complete', target: 1, questIds: [], treeIds: [] },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'quest-warrior' },
      update: {},
      create: {
        slug: 'quest-warrior',
        name: 'Quest Warrior',
        description: 'Complete 10 quests',
        icon: 'trophy',
        color: '#eab308',
        type: 'PROGRESS',
        rarity: 'UNCOMMON',
        criteria: { type: 'quest_complete', target: 10, questIds: [], treeIds: [] },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'quest-master' },
      update: {},
      create: {
        slug: 'quest-master',
        name: 'Quest Master',
        description: 'Complete 50 quests',
        icon: 'crown',
        color: '#a855f7',
        type: 'PROGRESS',
        rarity: 'EPIC',
        criteria: { type: 'quest_complete', target: 50, questIds: [], treeIds: [] },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'streak-starter' },
      update: {},
      create: {
        slug: 'streak-starter',
        name: 'Streak Starter',
        description: 'Maintain a 7-day streak',
        icon: 'flame',
        color: '#f97316',
        type: 'STREAK',
        rarity: 'COMMON',
        criteria: { type: 'streak', target: 7, questIds: [], treeIds: [] },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'on-fire' },
      update: {},
      create: {
        slug: 'on-fire',
        name: 'On Fire',
        description: 'Maintain a 30-day streak',
        icon: 'zap',
        color: '#ef4444',
        type: 'STREAK',
        rarity: 'RARE',
        criteria: { type: 'streak', target: 30, questIds: [], treeIds: [] },
      },
    }),
    // Skill badges
    prisma.badge.upsert({
      where: { slug: 'frontend-explorer' },
      update: {},
      create: {
        slug: 'frontend-explorer',
        name: 'Frontend Explorer',
        description: 'Complete 5 frontend quests',
        icon: 'palette',
        color: '#ec4899',
        type: 'SKILL',
        rarity: 'COMMON',
        criteria: { type: 'role_quests', target: 5, questIds: [], treeIds: [], conditions: '{"role":"FRONTEND"}' },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'backend-builder' },
      update: {},
      create: {
        slug: 'backend-builder',
        name: 'Backend Builder',
        description: 'Complete 5 backend quests',
        icon: 'server',
        color: '#22c55e',
        type: 'SKILL',
        rarity: 'COMMON',
        criteria: { type: 'role_quests', target: 5, questIds: [], treeIds: [], conditions: '{"role":"BACKEND"}' },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'devops-deployer' },
      update: {},
      create: {
        slug: 'devops-deployer',
        name: 'DevOps Deployer',
        description: 'Complete 5 DevOps quests',
        icon: 'wrench',
        color: '#f97316',
        type: 'SKILL',
        rarity: 'COMMON',
        criteria: { type: 'role_quests', target: 5, questIds: [], treeIds: [], conditions: '{"role":"DEVOPS"}' },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'security-sentinel' },
      update: {},
      create: {
        slug: 'security-sentinel',
        name: 'Security Sentinel',
        description: 'Complete 5 security quests',
        icon: 'shield',
        color: '#ef4444',
        type: 'SKILL',
        rarity: 'UNCOMMON',
        criteria: { type: 'role_quests', target: 5, questIds: [], treeIds: [], conditions: '{"role":"SECURITY"}' },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'fullstack-hero' },
      update: {},
      create: {
        slug: 'fullstack-hero',
        name: 'Fullstack Hero',
        description: 'Complete quests in both frontend and backend',
        icon: 'rocket',
        color: '#3b82f6',
        type: 'SKILL',
        rarity: 'RARE',
        criteria: { type: 'multi_role', target: 10, questIds: [], treeIds: [], conditions: '{"roles":["FRONTEND","BACKEND"]}' },
      },
    }),
    // Difficulty badges (using SPECIAL type)
    prisma.badge.upsert({
      where: { slug: 'master-challenger' },
      update: {},
      create: {
        slug: 'master-challenger',
        name: 'Master Challenger',
        description: 'Complete a Master difficulty quest',
        icon: 'star',
        color: '#a855f7',
        type: 'SPECIAL',
        rarity: 'LEGENDARY',
        criteria: { type: 'difficulty_complete', target: 1, questIds: [], treeIds: [], conditions: '{"difficulty":"MASTER"}' },
      },
    }),
    prisma.badge.upsert({
      where: { slug: 'expert-adventurer' },
      update: {},
      create: {
        slug: 'expert-adventurer',
        name: 'Expert Adventurer',
        description: 'Complete 5 Expert difficulty quests',
        icon: 'award',
        color: '#f59e0b',
        type: 'SPECIAL',
        rarity: 'EPIC',
        criteria: { type: 'difficulty_complete', target: 5, questIds: [], treeIds: [], conditions: '{"difficulty":"EXPERT"}' },
      },
    }),
  ])

  console.log(`Created ${badges.length} badges`)

  // ============================================
  // QUEST TREES
  // ============================================
  console.log('Creating quest trees...')

  const trees = {
    // FOUNDATIONS LAYER
    foundations: await prisma.questTree.upsert({
      where: { slug: 'foundations' },
      update: {},
      create: {
        slug: 'foundations',
        name: 'Foundations of Computing',
        description: 'Master the fundamental concepts of computer science and programming',
        icon: 'book-open',
        color: '#8b5cf6',
        difficulty: 'NOVICE',
        estimatedHours: 15,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND', 'DEVOPS', 'SECURITY'],
        prerequisiteTreeIds: [],
        order: 1,
        layer: 'FOUNDATIONS',
      },
    }),
    gitBasics: await prisma.questTree.upsert({
      where: { slug: 'git-basics' },
      update: {},
      create: {
        slug: 'git-basics',
        name: 'Git & Version Control',
        description: 'Learn to track changes and collaborate with Git',
        icon: 'git-branch',
        color: '#f97316',
        difficulty: 'NOVICE',
        estimatedHours: 8,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND', 'DEVOPS'],
        prerequisiteTreeIds: [],
        order: 2,
        layer: 'FOUNDATIONS',
      },
    }),
    terminalMastery: await prisma.questTree.upsert({
      where: { slug: 'terminal-mastery' },
      update: {},
      create: {
        slug: 'terminal-mastery',
        name: 'Terminal Mastery',
        description: 'Become proficient with the command line interface',
        icon: 'terminal',
        color: '#22c55e',
        difficulty: 'NOVICE',
        estimatedHours: 10,
        roleRelevance: ['FULLSTACK', 'BACKEND', 'DEVOPS', 'SECURITY'],
        prerequisiteTreeIds: [],
        order: 3,
        layer: 'FOUNDATIONS',
      },
    }),
    webFundamentals: await prisma.questTree.upsert({
      where: { slug: 'web-fundamentals' },
      update: {},
      create: {
        slug: 'web-fundamentals',
        name: 'Web Fundamentals',
        description: 'Understand how the web works - HTTP, DNS, and browsers',
        icon: 'globe',
        color: '#3b82f6',
        difficulty: 'NOVICE',
        estimatedHours: 12,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND', 'SECURITY'],
        prerequisiteTreeIds: [],
        order: 4,
        layer: 'FOUNDATIONS',
      },
    }),
    dataStructures: await prisma.questTree.upsert({
      where: { slug: 'data-structures' },
      update: {},
      create: {
        slug: 'data-structures',
        name: 'Data Structures',
        description: 'Master arrays, linked lists, trees, and more',
        icon: 'boxes',
        color: '#a855f7',
        difficulty: 'APPRENTICE',
        estimatedHours: 20,
        roleRelevance: ['FULLSTACK', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 5,
        layer: 'FOUNDATIONS',
      },
    }),

    // TOOL MASTERY LAYER - Frontend
    htmlCss: await prisma.questTree.upsert({
      where: { slug: 'html-css' },
      update: {},
      create: {
        slug: 'html-css',
        name: 'HTML & CSS Mastery',
        description: 'Build beautiful, semantic web pages',
        icon: 'layout',
        color: '#ec4899',
        difficulty: 'NOVICE',
        estimatedHours: 20,
        roleRelevance: ['FULLSTACK', 'FRONTEND'],
        prerequisiteTreeIds: [],
        order: 6,
        layer: 'TOOL_MASTERY',
      },
    }),
    javascript: await prisma.questTree.upsert({
      where: { slug: 'javascript' },
      update: {},
      create: {
        slug: 'javascript',
        name: 'JavaScript Essentials',
        description: 'Master the language of the web',
        icon: 'code',
        color: '#eab308',
        difficulty: 'APPRENTICE',
        estimatedHours: 30,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 7,
        layer: 'TOOL_MASTERY',
      },
    }),
    typescript: await prisma.questTree.upsert({
      where: { slug: 'typescript' },
      update: {},
      create: {
        slug: 'typescript',
        name: 'TypeScript Fundamentals',
        description: 'Add type safety to your JavaScript',
        icon: 'file-code',
        color: '#3b82f6',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 25,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 8,
        layer: 'TOOL_MASTERY',
      },
    }),
    react: await prisma.questTree.upsert({
      where: { slug: 'react' },
      update: {},
      create: {
        slug: 'react',
        name: 'React Development',
        description: 'Build modern user interfaces with React',
        icon: 'code2',
        color: '#06b6d4',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 35,
        roleRelevance: ['FULLSTACK', 'FRONTEND'],
        prerequisiteTreeIds: [],
        order: 9,
        layer: 'TOOL_MASTERY',
      },
    }),
    nextjs: await prisma.questTree.upsert({
      where: { slug: 'nextjs' },
      update: {},
      create: {
        slug: 'nextjs',
        name: 'Next.js Framework',
        description: 'Full-stack React applications with Next.js',
        icon: 'layers',
        color: '#000000',
        difficulty: 'EXPERT',
        estimatedHours: 40,
        roleRelevance: ['FULLSTACK', 'FRONTEND'],
        prerequisiteTreeIds: [],
        order: 10,
        layer: 'TOOL_MASTERY',
      },
    }),

    // TOOL MASTERY LAYER - Backend
    nodejs: await prisma.questTree.upsert({
      where: { slug: 'nodejs' },
      update: {},
      create: {
        slug: 'nodejs',
        name: 'Node.js Backend',
        description: 'Server-side JavaScript with Node.js',
        icon: 'server',
        color: '#22c55e',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 30,
        roleRelevance: ['FULLSTACK', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 11,
        layer: 'TOOL_MASTERY',
      },
    }),
    databases: await prisma.questTree.upsert({
      where: { slug: 'databases' },
      update: {},
      create: {
        slug: 'databases',
        name: 'Database Fundamentals',
        description: 'SQL, NoSQL, and data modeling',
        icon: 'database',
        color: '#8b5cf6',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 35,
        roleRelevance: ['FULLSTACK', 'BACKEND', 'DEVOPS'],
        prerequisiteTreeIds: [],
        order: 12,
        layer: 'TOOL_MASTERY',
      },
    }),
    apis: await prisma.questTree.upsert({
      where: { slug: 'apis' },
      update: {},
      create: {
        slug: 'apis',
        name: 'API Design & Development',
        description: 'Build RESTful and GraphQL APIs',
        icon: 'send',
        color: '#14b8a6',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 25,
        roleRelevance: ['FULLSTACK', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 13,
        layer: 'TOOL_MASTERY',
      },
    }),
    authentication: await prisma.questTree.upsert({
      where: { slug: 'authentication' },
      update: {},
      create: {
        slug: 'authentication',
        name: 'Authentication & Authorization',
        description: 'Secure user identity and access control',
        icon: 'lock',
        color: '#ef4444',
        difficulty: 'EXPERT',
        estimatedHours: 20,
        roleRelevance: ['FULLSTACK', 'BACKEND', 'SECURITY'],
        prerequisiteTreeIds: [],
        order: 14,
        layer: 'TOOL_MASTERY',
      },
    }),

    // TOOL MASTERY LAYER - DevOps
    docker: await prisma.questTree.upsert({
      where: { slug: 'docker' },
      update: {},
      create: {
        slug: 'docker',
        name: 'Docker Containers',
        description: 'Containerize applications with Docker',
        icon: 'box',
        color: '#2563eb',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 20,
        roleRelevance: ['FULLSTACK', 'BACKEND', 'DEVOPS'],
        prerequisiteTreeIds: [],
        order: 15,
        layer: 'TOOL_MASTERY',
      },
    }),
    cicd: await prisma.questTree.upsert({
      where: { slug: 'cicd' },
      update: {},
      create: {
        slug: 'cicd',
        name: 'CI/CD Pipelines',
        description: 'Automate build, test, and deployment',
        icon: 'play-circle',
        color: '#f97316',
        difficulty: 'EXPERT',
        estimatedHours: 25,
        roleRelevance: ['DEVOPS', 'FULLSTACK'],
        prerequisiteTreeIds: [],
        order: 16,
        layer: 'TOOL_MASTERY',
      },
    }),
    cloudBasics: await prisma.questTree.upsert({
      where: { slug: 'cloud-basics' },
      update: {},
      create: {
        slug: 'cloud-basics',
        name: 'Cloud Computing Basics',
        description: 'Introduction to AWS, Azure, and GCP',
        icon: 'cloud',
        color: '#06b6d4',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 30,
        roleRelevance: ['DEVOPS', 'BACKEND', 'FULLSTACK'],
        prerequisiteTreeIds: [],
        order: 17,
        layer: 'TOOL_MASTERY',
      },
    }),
    kubernetes: await prisma.questTree.upsert({
      where: { slug: 'kubernetes' },
      update: {},
      create: {
        slug: 'kubernetes',
        name: 'Kubernetes Orchestration',
        description: 'Container orchestration at scale',
        icon: 'blocks',
        color: '#326ce5',
        difficulty: 'EXPERT',
        estimatedHours: 40,
        roleRelevance: ['DEVOPS'],
        prerequisiteTreeIds: [],
        order: 18,
        layer: 'TOOL_MASTERY',
      },
    }),

    // SPECIALIZATION LAYER
    testing: await prisma.questTree.upsert({
      where: { slug: 'testing' },
      update: {},
      create: {
        slug: 'testing',
        name: 'Testing Strategies',
        description: 'Unit, integration, and E2E testing',
        icon: 'test-tube',
        color: '#22c55e',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 25,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 19,
        layer: 'SPECIALIZATION',
      },
    }),
    security: await prisma.questTree.upsert({
      where: { slug: 'security' },
      update: {},
      create: {
        slug: 'security',
        name: 'Web Security',
        description: 'Protect against OWASP vulnerabilities',
        icon: 'shield',
        color: '#ef4444',
        difficulty: 'EXPERT',
        estimatedHours: 30,
        roleRelevance: ['SECURITY', 'FULLSTACK', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 20,
        layer: 'SPECIALIZATION',
      },
    }),
    performance: await prisma.questTree.upsert({
      where: { slug: 'performance' },
      update: {},
      create: {
        slug: 'performance',
        name: 'Performance Optimization',
        description: 'Make applications lightning fast',
        icon: 'zap',
        color: '#eab308',
        difficulty: 'EXPERT',
        estimatedHours: 25,
        roleRelevance: ['FULLSTACK', 'FRONTEND', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 21,
        layer: 'SPECIALIZATION',
      },
    }),
    monitoring: await prisma.questTree.upsert({
      where: { slug: 'monitoring' },
      update: {},
      create: {
        slug: 'monitoring',
        name: 'Monitoring & Observability',
        description: 'Logging, metrics, and tracing',
        icon: 'activity',
        color: '#8b5cf6',
        difficulty: 'EXPERT',
        estimatedHours: 20,
        roleRelevance: ['DEVOPS', 'BACKEND'],
        prerequisiteTreeIds: [],
        order: 22,
        layer: 'SPECIALIZATION',
      },
    }),
    systemDesign: await prisma.questTree.upsert({
      where: { slug: 'system-design' },
      update: {},
      create: {
        slug: 'system-design',
        name: 'System Design',
        description: 'Design scalable distributed systems',
        icon: 'compass',
        color: '#6366f1',
        difficulty: 'MASTER',
        estimatedHours: 50,
        roleRelevance: ['BACKEND', 'FULLSTACK', 'DEVOPS'],
        prerequisiteTreeIds: [],
        order: 23,
        layer: 'SPECIALIZATION',
      },
    }),

    // CAPSTONE LAYER
    fullstackProject: await prisma.questTree.upsert({
      where: { slug: 'fullstack-project' },
      update: {},
      create: {
        slug: 'fullstack-project',
        name: 'Fullstack Capstone',
        description: 'Build a complete production application',
        icon: 'rocket',
        color: '#3b82f6',
        difficulty: 'MASTER',
        estimatedHours: 60,
        roleRelevance: ['FULLSTACK'],
        prerequisiteTreeIds: [],
        order: 24,
        layer: 'CAPSTONE',
      },
    }),
    devopsProject: await prisma.questTree.upsert({
      where: { slug: 'devops-project' },
      update: {},
      create: {
        slug: 'devops-project',
        name: 'DevOps Capstone',
        description: 'Build a complete CI/CD infrastructure',
        icon: 'wrench',
        color: '#f97316',
        difficulty: 'MASTER',
        estimatedHours: 50,
        roleRelevance: ['DEVOPS'],
        prerequisiteTreeIds: [],
        order: 25,
        layer: 'CAPSTONE',
      },
    }),
  }

  console.log(`Created ${Object.keys(trees).length} quest trees`)

  // ============================================
  // QUESTS
  // ============================================
  console.log('Creating quests...')

  const quests = await Promise.all([
    // FOUNDATIONS TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'hello-world' },
      update: {},
      create: {
        slug: 'hello-world',
        name: 'Hello World',
        description: 'Write your first program and understand how code executes',
        difficulty: 'NOVICE',
        estimatedHours: 1,
        xpReward: 50,
        treeId: trees.foundations.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Set up environment', description: 'Install Node.js or Python', order: 1, hints: ['Visit nodejs.org or python.org'] },
          { id: 't2', name: 'Create file', description: 'Create a new file for your code', order: 2, hints: [] },
          { id: 't3', name: 'Write code', description: 'Print "Hello, World!" to the console', order: 3, hints: ['Use console.log() or print()'] },
          { id: 't4', name: 'Run program', description: 'Execute your code and verify output', order: 4, hints: [] },
        ],
        learningObjectives: ['Understand program execution', 'Use a code editor', 'Run code from terminal'],
        resources: [{ type: 'DOCUMENT', name: 'Node.js Docs', url: 'https://nodejs.org/docs' }],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'variables-types' },
      update: {},
      create: {
        slug: 'variables-types',
        name: 'Variables & Data Types',
        description: 'Learn how to store and manipulate data',
        difficulty: 'NOVICE',
        estimatedHours: 2,
        xpReward: 75,
        treeId: trees.foundations.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Declare variables', description: 'Create variables using let, const, var', order: 1, hints: [] },
          { id: 't2', name: 'Explore types', description: 'Work with strings, numbers, booleans', order: 2, hints: [] },
          { id: 't3', name: 'Type conversion', description: 'Convert between different types', order: 3, hints: [] },
        ],
        learningObjectives: ['Understand variable declaration', 'Know primitive data types', 'Perform type conversions'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'control-flow' },
      update: {},
      create: {
        slug: 'control-flow',
        name: 'Control Flow',
        description: 'Master conditionals and loops',
        difficulty: 'NOVICE',
        estimatedHours: 3,
        xpReward: 100,
        treeId: trees.foundations.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'If statements', description: 'Write conditional logic', order: 1, hints: [] },
          { id: 't2', name: 'Switch cases', description: 'Handle multiple conditions', order: 2, hints: [] },
          { id: 't3', name: 'For loops', description: 'Iterate over collections', order: 3, hints: [] },
          { id: 't4', name: 'While loops', description: 'Loop with conditions', order: 4, hints: [] },
        ],
        learningObjectives: ['Write conditional statements', 'Use different loop types', 'Avoid infinite loops'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'functions-basics' },
      update: {},
      create: {
        slug: 'functions-basics',
        name: 'Functions Fundamentals',
        description: 'Create reusable blocks of code',
        difficulty: 'APPRENTICE',
        estimatedHours: 3,
        xpReward: 125,
        treeId: trees.foundations.id,
        prerequisiteQuestIds: [],
        order: 4,
        tasks: [
          { id: 't1', name: 'Define functions', description: 'Create function declarations', order: 1, hints: [] },
          { id: 't2', name: 'Parameters', description: 'Pass data to functions', order: 2, hints: [] },
          { id: 't3', name: 'Return values', description: 'Get results from functions', order: 3, hints: [] },
          { id: 't4', name: 'Arrow functions', description: 'Use modern syntax', order: 4, hints: [] },
        ],
        learningObjectives: ['Create and call functions', 'Understand scope', 'Use arrow function syntax'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'debugging-101' },
      update: {},
      create: {
        slug: 'debugging-101',
        name: 'Debugging 101',
        description: 'Learn to find and fix bugs in code',
        difficulty: 'APPRENTICE',
        estimatedHours: 2,
        xpReward: 100,
        treeId: trees.foundations.id,
        prerequisiteQuestIds: [],
        order: 5,
        tasks: [
          { id: 't1', name: 'Console logging', description: 'Use console.log for debugging', order: 1, hints: [] },
          { id: 't2', name: 'Read errors', description: 'Understand error messages', order: 2, hints: [] },
          { id: 't3', name: 'Debugger', description: 'Use browser/IDE debugger', order: 3, hints: [] },
        ],
        learningObjectives: ['Read stack traces', 'Set breakpoints', 'Debug systematically'],
        resources: [],
      },
    }),

    // GIT BASICS TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'git-init' },
      update: {},
      create: {
        slug: 'git-init',
        name: 'Git Init',
        description: 'Initialize your first Git repository',
        difficulty: 'NOVICE',
        estimatedHours: 1,
        xpReward: 50,
        treeId: trees.gitBasics.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Install Git', description: 'Download and install Git', order: 1, hints: [] },
          { id: 't2', name: 'Configure Git', description: 'Set your name and email', order: 2, hints: ['git config --global user.name'] },
          { id: 't3', name: 'Init repo', description: 'Create a new repository', order: 3, hints: ['git init'] },
        ],
        learningObjectives: ['Install and configure Git', 'Initialize repositories', 'Understand .git folder'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'commit-basics' },
      update: {},
      create: {
        slug: 'commit-basics',
        name: 'Commit Basics',
        description: 'Stage and commit your changes',
        difficulty: 'NOVICE',
        estimatedHours: 1,
        xpReward: 75,
        treeId: trees.gitBasics.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Check status', description: 'View repository status', order: 1, hints: ['git status'] },
          { id: 't2', name: 'Stage files', description: 'Add files to staging', order: 2, hints: ['git add'] },
          { id: 't3', name: 'Commit changes', description: 'Create a commit', order: 3, hints: ['git commit -m "message"'] },
          { id: 't4', name: 'View history', description: 'See commit log', order: 4, hints: ['git log'] },
        ],
        learningObjectives: ['Stage and commit changes', 'Write good commit messages', 'View commit history'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'branching-merging' },
      update: {},
      create: {
        slug: 'branching-merging',
        name: 'Branching & Merging',
        description: 'Work with branches and merge changes',
        difficulty: 'APPRENTICE',
        estimatedHours: 2,
        xpReward: 100,
        treeId: trees.gitBasics.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Create branch', description: 'Make a new branch', order: 1, hints: ['git branch feature'] },
          { id: 't2', name: 'Switch branches', description: 'Move between branches', order: 2, hints: ['git checkout'] },
          { id: 't3', name: 'Merge branches', description: 'Combine branch changes', order: 3, hints: ['git merge'] },
          { id: 't4', name: 'Delete branch', description: 'Clean up merged branches', order: 4, hints: [] },
        ],
        learningObjectives: ['Create and manage branches', 'Merge changes', 'Understand branch strategies'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'remote-repos' },
      update: {},
      create: {
        slug: 'remote-repos',
        name: 'Remote Repositories',
        description: 'Push and pull from GitHub',
        difficulty: 'APPRENTICE',
        estimatedHours: 2,
        xpReward: 100,
        treeId: trees.gitBasics.id,
        prerequisiteQuestIds: [],
        order: 4,
        tasks: [
          { id: 't1', name: 'Create GitHub repo', description: 'Set up remote repository', order: 1, hints: [] },
          { id: 't2', name: 'Add remote', description: 'Connect local to remote', order: 2, hints: ['git remote add origin'] },
          { id: 't3', name: 'Push code', description: 'Upload your changes', order: 3, hints: ['git push'] },
          { id: 't4', name: 'Pull changes', description: 'Download updates', order: 4, hints: ['git pull'] },
        ],
        learningObjectives: ['Work with remote repositories', 'Push and pull changes', 'Understand origin'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'resolve-conflicts' },
      update: {},
      create: {
        slug: 'resolve-conflicts',
        name: 'Resolving Conflicts',
        description: 'Handle merge conflicts like a pro',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 2,
        xpReward: 150,
        treeId: trees.gitBasics.id,
        prerequisiteQuestIds: [],
        order: 5,
        tasks: [
          { id: 't1', name: 'Create conflict', description: 'Simulate a merge conflict', order: 1, hints: [] },
          { id: 't2', name: 'Identify conflicts', description: 'Find conflicting files', order: 2, hints: [] },
          { id: 't3', name: 'Resolve manually', description: 'Edit and fix conflicts', order: 3, hints: [] },
          { id: 't4', name: 'Complete merge', description: 'Finish the merge', order: 4, hints: [] },
        ],
        learningObjectives: ['Identify merge conflicts', 'Resolve conflicts manually', 'Prevent common conflicts'],
        resources: [],
      },
    }),

    // HTML & CSS TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'html-structure' },
      update: {},
      create: {
        slug: 'html-structure',
        name: 'HTML Document Structure',
        description: 'Build semantic HTML pages',
        difficulty: 'NOVICE',
        estimatedHours: 2,
        xpReward: 75,
        treeId: trees.htmlCss.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'DOCTYPE & head', description: 'Set up document structure', order: 1, hints: [] },
          { id: 't2', name: 'Semantic tags', description: 'Use header, main, footer', order: 2, hints: [] },
          { id: 't3', name: 'Text elements', description: 'Add headings and paragraphs', order: 3, hints: [] },
          { id: 't4', name: 'Links & images', description: 'Insert media and navigation', order: 4, hints: [] },
        ],
        learningObjectives: ['Write semantic HTML', 'Structure documents correctly', 'Use appropriate elements'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'css-selectors' },
      update: {},
      create: {
        slug: 'css-selectors',
        name: 'CSS Selectors & Specificity',
        description: 'Target elements with precision',
        difficulty: 'NOVICE',
        estimatedHours: 2,
        xpReward: 75,
        treeId: trees.htmlCss.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Element selectors', description: 'Select by tag name', order: 1, hints: [] },
          { id: 't2', name: 'Class selectors', description: 'Use .class notation', order: 2, hints: [] },
          { id: 't3', name: 'ID selectors', description: 'Target specific elements', order: 3, hints: [] },
          { id: 't4', name: 'Combinators', description: 'Chain selectors together', order: 4, hints: [] },
        ],
        learningObjectives: ['Use different selector types', 'Understand specificity', 'Write efficient selectors'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'flexbox-layout' },
      update: {},
      create: {
        slug: 'flexbox-layout',
        name: 'Flexbox Layout',
        description: 'Create flexible layouts with ease',
        difficulty: 'APPRENTICE',
        estimatedHours: 3,
        xpReward: 125,
        treeId: trees.htmlCss.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Flex container', description: 'Enable flexbox on parent', order: 1, hints: ['display: flex'] },
          { id: 't2', name: 'Direction & wrap', description: 'Control flow direction', order: 2, hints: [] },
          { id: 't3', name: 'Justify content', description: 'Align items horizontally', order: 3, hints: [] },
          { id: 't4', name: 'Align items', description: 'Align items vertically', order: 4, hints: [] },
        ],
        learningObjectives: ['Use flexbox properties', 'Create responsive layouts', 'Center elements easily'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'css-grid' },
      update: {},
      create: {
        slug: 'css-grid',
        name: 'CSS Grid Mastery',
        description: 'Build complex grid layouts',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.htmlCss.id,
        prerequisiteQuestIds: [],
        order: 4,
        tasks: [
          { id: 't1', name: 'Grid container', description: 'Set up grid layout', order: 1, hints: ['display: grid'] },
          { id: 't2', name: 'Columns & rows', description: 'Define grid tracks', order: 2, hints: [] },
          { id: 't3', name: 'Grid areas', description: 'Name and place areas', order: 3, hints: [] },
          { id: 't4', name: 'Responsive grid', description: 'Make grids responsive', order: 4, hints: [] },
        ],
        learningObjectives: ['Create grid layouts', 'Use grid areas', 'Build responsive grids'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'responsive-design' },
      update: {},
      create: {
        slug: 'responsive-design',
        name: 'Responsive Design',
        description: 'Build mobile-first responsive sites',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.htmlCss.id,
        prerequisiteQuestIds: [],
        order: 5,
        tasks: [
          { id: 't1', name: 'Viewport meta', description: 'Set up responsive viewport', order: 1, hints: [] },
          { id: 't2', name: 'Media queries', description: 'Write breakpoint styles', order: 2, hints: [] },
          { id: 't3', name: 'Mobile first', description: 'Start with mobile styles', order: 3, hints: [] },
          { id: 't4', name: 'Responsive images', description: 'Handle images responsively', order: 4, hints: [] },
        ],
        learningObjectives: ['Write media queries', 'Design mobile-first', 'Handle responsive images'],
        resources: [],
      },
    }),

    // JAVASCRIPT TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'js-arrays' },
      update: {},
      create: {
        slug: 'js-arrays',
        name: 'Arrays & Array Methods',
        description: 'Master JavaScript arrays',
        difficulty: 'APPRENTICE',
        estimatedHours: 3,
        xpReward: 125,
        treeId: trees.javascript.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Create arrays', description: 'Initialize arrays', order: 1, hints: [] },
          { id: 't2', name: 'Map & filter', description: 'Transform and filter data', order: 2, hints: [] },
          { id: 't3', name: 'Reduce', description: 'Aggregate array values', order: 3, hints: [] },
          { id: 't4', name: 'Spread operator', description: 'Copy and merge arrays', order: 4, hints: [] },
        ],
        learningObjectives: ['Use array methods', 'Transform data functionally', 'Understand immutability'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'js-objects' },
      update: {},
      create: {
        slug: 'js-objects',
        name: 'Objects & Prototypes',
        description: 'Work with JavaScript objects',
        difficulty: 'APPRENTICE',
        estimatedHours: 3,
        xpReward: 125,
        treeId: trees.javascript.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Object literals', description: 'Create objects', order: 1, hints: [] },
          { id: 't2', name: 'Destructuring', description: 'Extract object properties', order: 2, hints: [] },
          { id: 't3', name: 'Object methods', description: 'Use Object.keys, values, entries', order: 3, hints: [] },
          { id: 't4', name: 'Prototypes', description: 'Understand prototype chain', order: 4, hints: [] },
        ],
        learningObjectives: ['Work with objects', 'Use destructuring', 'Understand prototypes'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'async-await' },
      update: {},
      create: {
        slug: 'async-await',
        name: 'Async/Await & Promises',
        description: 'Handle asynchronous operations',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.javascript.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Callbacks', description: 'Understand callback pattern', order: 1, hints: [] },
          { id: 't2', name: 'Promises', description: 'Create and chain promises', order: 2, hints: [] },
          { id: 't3', name: 'Async/await', description: 'Write async functions', order: 3, hints: [] },
          { id: 't4', name: 'Error handling', description: 'Handle async errors', order: 4, hints: ['try/catch'] },
        ],
        learningObjectives: ['Work with Promises', 'Use async/await', 'Handle async errors'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'dom-manipulation' },
      update: {},
      create: {
        slug: 'dom-manipulation',
        name: 'DOM Manipulation',
        description: 'Interact with web pages dynamically',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.javascript.id,
        prerequisiteQuestIds: [],
        order: 4,
        tasks: [
          { id: 't1', name: 'Select elements', description: 'Use querySelector', order: 1, hints: [] },
          { id: 't2', name: 'Modify content', description: 'Change text and HTML', order: 2, hints: [] },
          { id: 't3', name: 'Event listeners', description: 'Handle user interactions', order: 3, hints: [] },
          { id: 't4', name: 'Create elements', description: 'Dynamically add elements', order: 4, hints: [] },
        ],
        learningObjectives: ['Select DOM elements', 'Handle events', 'Create dynamic content'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'es6-modules' },
      update: {},
      create: {
        slug: 'es6-modules',
        name: 'ES6 Modules',
        description: 'Organize code with modules',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 2,
        xpReward: 125,
        treeId: trees.javascript.id,
        prerequisiteQuestIds: [],
        order: 5,
        tasks: [
          { id: 't1', name: 'Export', description: 'Export functions and classes', order: 1, hints: [] },
          { id: 't2', name: 'Import', description: 'Import from other modules', order: 2, hints: [] },
          { id: 't3', name: 'Default exports', description: 'Use default exports', order: 3, hints: [] },
          { id: 't4', name: 'Re-exports', description: 'Create barrel files', order: 4, hints: [] },
        ],
        learningObjectives: ['Use ES6 modules', 'Organize code properly', 'Create module patterns'],
        resources: [],
      },
    }),

    // REACT TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'react-components' },
      update: {},
      create: {
        slug: 'react-components',
        name: 'React Components',
        description: 'Build reusable UI components',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.react.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Function components', description: 'Create functional components', order: 1, hints: [] },
          { id: 't2', name: 'Props', description: 'Pass data to components', order: 2, hints: [] },
          { id: 't3', name: 'Children', description: 'Use children prop', order: 3, hints: [] },
          { id: 't4', name: 'Composition', description: 'Compose components together', order: 4, hints: [] },
        ],
        learningObjectives: ['Create React components', 'Use props effectively', 'Compose UIs'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'react-state' },
      update: {},
      create: {
        slug: 'react-state',
        name: 'State Management',
        description: 'Manage component state with hooks',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.react.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'useState', description: 'Manage local state', order: 1, hints: [] },
          { id: 't2', name: 'useEffect', description: 'Handle side effects', order: 2, hints: [] },
          { id: 't3', name: 'useContext', description: 'Share state globally', order: 3, hints: [] },
          { id: 't4', name: 'useReducer', description: 'Complex state logic', order: 4, hints: [] },
        ],
        learningObjectives: ['Use React hooks', 'Manage state properly', 'Handle side effects'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'react-forms' },
      update: {},
      create: {
        slug: 'react-forms',
        name: 'Forms & Validation',
        description: 'Build forms with React',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.react.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Controlled inputs', description: 'Create controlled components', order: 1, hints: [] },
          { id: 't2', name: 'Form handling', description: 'Handle form submission', order: 2, hints: [] },
          { id: 't3', name: 'Validation', description: 'Add form validation', order: 3, hints: [] },
          { id: 't4', name: 'Error display', description: 'Show validation errors', order: 4, hints: [] },
        ],
        learningObjectives: ['Create forms in React', 'Validate user input', 'Handle form state'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'react-routing' },
      update: {},
      create: {
        slug: 'react-routing',
        name: 'Client-Side Routing',
        description: 'Add navigation to React apps',
        difficulty: 'EXPERT',
        estimatedHours: 3,
        xpReward: 175,
        treeId: trees.react.id,
        prerequisiteQuestIds: [],
        order: 4,
        tasks: [
          { id: 't1', name: 'Setup router', description: 'Install and configure router', order: 1, hints: [] },
          { id: 't2', name: 'Define routes', description: 'Create route definitions', order: 2, hints: [] },
          { id: 't3', name: 'Navigation', description: 'Add links and navigation', order: 3, hints: [] },
          { id: 't4', name: 'Route params', description: 'Handle dynamic routes', order: 4, hints: [] },
        ],
        learningObjectives: ['Set up React Router', 'Create dynamic routes', 'Handle navigation'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'react-performance' },
      update: {},
      create: {
        slug: 'react-performance',
        name: 'React Performance',
        description: 'Optimize React applications',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.react.id,
        prerequisiteQuestIds: [],
        order: 5,
        tasks: [
          { id: 't1', name: 'useMemo', description: 'Memoize expensive computations', order: 1, hints: [] },
          { id: 't2', name: 'useCallback', description: 'Memoize callbacks', order: 2, hints: [] },
          { id: 't3', name: 'React.memo', description: 'Prevent re-renders', order: 3, hints: [] },
          { id: 't4', name: 'Code splitting', description: 'Lazy load components', order: 4, hints: [] },
        ],
        learningObjectives: ['Optimize React apps', 'Prevent unnecessary renders', 'Use code splitting'],
        resources: [],
      },
    }),

    // NODE.JS TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'node-basics' },
      update: {},
      create: {
        slug: 'node-basics',
        name: 'Node.js Basics',
        description: 'Run JavaScript on the server',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.nodejs.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Node REPL', description: 'Use Node.js interactively', order: 1, hints: [] },
          { id: 't2', name: 'File system', description: 'Read and write files', order: 2, hints: [] },
          { id: 't3', name: 'NPM basics', description: 'Manage packages', order: 3, hints: [] },
          { id: 't4', name: 'Package.json', description: 'Configure your project', order: 4, hints: [] },
        ],
        learningObjectives: ['Use Node.js runtime', 'Work with npm', 'Handle file system'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'express-server' },
      update: {},
      create: {
        slug: 'express-server',
        name: 'Express Server',
        description: 'Build web servers with Express',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.nodejs.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Setup Express', description: 'Create Express app', order: 1, hints: [] },
          { id: 't2', name: 'Routes', description: 'Define API routes', order: 2, hints: [] },
          { id: 't3', name: 'Middleware', description: 'Use middleware functions', order: 3, hints: [] },
          { id: 't4', name: 'Error handling', description: 'Handle errors properly', order: 4, hints: [] },
        ],
        learningObjectives: ['Create Express servers', 'Define routes', 'Use middleware'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'rest-api' },
      update: {},
      create: {
        slug: 'rest-api',
        name: 'RESTful API Design',
        description: 'Design and build REST APIs',
        difficulty: 'EXPERT',
        estimatedHours: 5,
        xpReward: 225,
        treeId: trees.nodejs.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'REST principles', description: 'Understand REST architecture', order: 1, hints: [] },
          { id: 't2', name: 'CRUD operations', description: 'Implement create, read, update, delete', order: 2, hints: [] },
          { id: 't3', name: 'Status codes', description: 'Use proper HTTP status codes', order: 3, hints: [] },
          { id: 't4', name: 'Validation', description: 'Validate request data', order: 4, hints: [] },
        ],
        learningObjectives: ['Design REST APIs', 'Follow REST conventions', 'Handle CRUD operations'],
        resources: [],
      },
    }),

    // DATABASE TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'sql-basics' },
      update: {},
      create: {
        slug: 'sql-basics',
        name: 'SQL Fundamentals',
        description: 'Query relational databases',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.databases.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'SELECT queries', description: 'Retrieve data from tables', order: 1, hints: [] },
          { id: 't2', name: 'INSERT/UPDATE', description: 'Modify data', order: 2, hints: [] },
          { id: 't3', name: 'JOINs', description: 'Combine tables', order: 3, hints: [] },
          { id: 't4', name: 'Aggregation', description: 'Use GROUP BY and functions', order: 4, hints: [] },
        ],
        learningObjectives: ['Write SQL queries', 'Join tables', 'Aggregate data'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'mongodb-basics' },
      update: {},
      create: {
        slug: 'mongodb-basics',
        name: 'MongoDB Essentials',
        description: 'Work with document databases',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.databases.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Documents', description: 'Understand document model', order: 1, hints: [] },
          { id: 't2', name: 'CRUD operations', description: 'Insert, find, update, delete', order: 2, hints: [] },
          { id: 't3', name: 'Queries', description: 'Filter and project data', order: 3, hints: [] },
          { id: 't4', name: 'Indexes', description: 'Create indexes for performance', order: 4, hints: [] },
        ],
        learningObjectives: ['Use MongoDB', 'Design document schemas', 'Query efficiently'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'prisma-orm' },
      update: {},
      create: {
        slug: 'prisma-orm',
        name: 'Prisma ORM',
        description: 'Type-safe database access',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.databases.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Schema definition', description: 'Define Prisma schema', order: 1, hints: [] },
          { id: 't2', name: 'Migrations', description: 'Create database migrations', order: 2, hints: [] },
          { id: 't3', name: 'Client usage', description: 'Use Prisma Client', order: 3, hints: [] },
          { id: 't4', name: 'Relations', description: 'Handle related data', order: 4, hints: [] },
        ],
        learningObjectives: ['Use Prisma ORM', 'Define schemas', 'Handle relations'],
        resources: [],
      },
    }),

    // DOCKER TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'docker-basics' },
      update: {},
      create: {
        slug: 'docker-basics',
        name: 'Docker Fundamentals',
        description: 'Containerize your applications',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.docker.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Install Docker', description: 'Set up Docker Desktop', order: 1, hints: [] },
          { id: 't2', name: 'Run containers', description: 'Use docker run', order: 2, hints: [] },
          { id: 't3', name: 'Images', description: 'Pull and list images', order: 3, hints: [] },
          { id: 't4', name: 'Container management', description: 'Start, stop, remove containers', order: 4, hints: [] },
        ],
        learningObjectives: ['Run Docker containers', 'Manage images', 'Understand containerization'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'dockerfile' },
      update: {},
      create: {
        slug: 'dockerfile',
        name: 'Writing Dockerfiles',
        description: 'Create custom Docker images',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.docker.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'FROM instruction', description: 'Choose base image', order: 1, hints: [] },
          { id: 't2', name: 'COPY and RUN', description: 'Add files and run commands', order: 2, hints: [] },
          { id: 't3', name: 'Build image', description: 'Build your custom image', order: 3, hints: [] },
          { id: 't4', name: 'Multi-stage', description: 'Use multi-stage builds', order: 4, hints: [] },
        ],
        learningObjectives: ['Write Dockerfiles', 'Build custom images', 'Optimize builds'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'docker-compose' },
      update: {},
      create: {
        slug: 'docker-compose',
        name: 'Docker Compose',
        description: 'Orchestrate multi-container applications',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.docker.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Compose file', description: 'Write docker-compose.yml', order: 1, hints: [] },
          { id: 't2', name: 'Services', description: 'Define multiple services', order: 2, hints: [] },
          { id: 't3', name: 'Networking', description: 'Connect containers', order: 3, hints: [] },
          { id: 't4', name: 'Volumes', description: 'Persist data', order: 4, hints: [] },
        ],
        learningObjectives: ['Use Docker Compose', 'Define services', 'Manage multi-container apps'],
        resources: [],
      },
    }),

    // SECURITY TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'security-basics' },
      update: {},
      create: {
        slug: 'security-basics',
        name: 'Web Security Basics',
        description: 'Understand common vulnerabilities',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.security.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'OWASP Top 10', description: 'Learn common vulnerabilities', order: 1, hints: [] },
          { id: 't2', name: 'XSS prevention', description: 'Prevent cross-site scripting', order: 2, hints: [] },
          { id: 't3', name: 'CSRF tokens', description: 'Implement CSRF protection', order: 3, hints: [] },
          { id: 't4', name: 'Input validation', description: 'Sanitize user input', order: 4, hints: [] },
        ],
        learningObjectives: ['Understand OWASP Top 10', 'Prevent common attacks', 'Validate input safely'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'secure-authentication' },
      update: {},
      create: {
        slug: 'secure-authentication',
        name: 'Secure Authentication',
        description: 'Implement secure auth flows',
        difficulty: 'EXPERT',
        estimatedHours: 5,
        xpReward: 225,
        treeId: trees.security.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Password hashing', description: 'Hash passwords securely', order: 1, hints: ['bcrypt'] },
          { id: 't2', name: 'JWT tokens', description: 'Implement JWT authentication', order: 2, hints: [] },
          { id: 't3', name: 'OAuth 2.0', description: 'Add social authentication', order: 3, hints: [] },
          { id: 't4', name: 'Session management', description: 'Handle sessions securely', order: 4, hints: [] },
        ],
        learningObjectives: ['Hash passwords', 'Use JWTs', 'Implement OAuth'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'sql-injection' },
      update: {},
      create: {
        slug: 'sql-injection',
        name: 'SQL Injection Prevention',
        description: 'Protect against SQL injection',
        difficulty: 'EXPERT',
        estimatedHours: 3,
        xpReward: 200,
        treeId: trees.security.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Understand SQLi', description: 'Learn how SQL injection works', order: 1, hints: [] },
          { id: 't2', name: 'Parameterized queries', description: 'Use prepared statements', order: 2, hints: [] },
          { id: 't3', name: 'ORM usage', description: 'Use ORMs safely', order: 3, hints: [] },
          { id: 't4', name: 'Testing', description: 'Test for vulnerabilities', order: 4, hints: [] },
        ],
        learningObjectives: ['Understand SQL injection', 'Use parameterized queries', 'Test for SQLi'],
        resources: [],
      },
    }),

    // TESTING TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'unit-testing' },
      update: {},
      create: {
        slug: 'unit-testing',
        name: 'Unit Testing',
        description: 'Test individual units of code',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.testing.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Setup Jest', description: 'Configure testing framework', order: 1, hints: [] },
          { id: 't2', name: 'Write tests', description: 'Create test cases', order: 2, hints: [] },
          { id: 't3', name: 'Assertions', description: 'Use expect matchers', order: 3, hints: [] },
          { id: 't4', name: 'Mocking', description: 'Mock dependencies', order: 4, hints: [] },
        ],
        learningObjectives: ['Write unit tests', 'Use Jest', 'Mock dependencies'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'integration-testing' },
      update: {},
      create: {
        slug: 'integration-testing',
        name: 'Integration Testing',
        description: 'Test component interactions',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.testing.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Test setup', description: 'Configure integration tests', order: 1, hints: [] },
          { id: 't2', name: 'API testing', description: 'Test API endpoints', order: 2, hints: [] },
          { id: 't3', name: 'Database testing', description: 'Test with real database', order: 3, hints: [] },
          { id: 't4', name: 'Test isolation', description: 'Isolate test data', order: 4, hints: [] },
        ],
        learningObjectives: ['Write integration tests', 'Test APIs', 'Manage test data'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'e2e-testing' },
      update: {},
      create: {
        slug: 'e2e-testing',
        name: 'End-to-End Testing',
        description: 'Test complete user flows',
        difficulty: 'EXPERT',
        estimatedHours: 5,
        xpReward: 225,
        treeId: trees.testing.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Setup Playwright', description: 'Configure E2E framework', order: 1, hints: [] },
          { id: 't2', name: 'Page objects', description: 'Create page object models', order: 2, hints: [] },
          { id: 't3', name: 'User flows', description: 'Test complete journeys', order: 3, hints: [] },
          { id: 't4', name: 'CI integration', description: 'Run tests in CI', order: 4, hints: [] },
        ],
        learningObjectives: ['Write E2E tests', 'Use Playwright', 'Implement page objects'],
        resources: [],
      },
    }),

    // CI/CD TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'github-actions' },
      update: {},
      create: {
        slug: 'github-actions',
        name: 'GitHub Actions',
        description: 'Automate workflows with GitHub',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 4,
        xpReward: 175,
        treeId: trees.cicd.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Workflow file', description: 'Create workflow YAML', order: 1, hints: [] },
          { id: 't2', name: 'Triggers', description: 'Configure workflow triggers', order: 2, hints: [] },
          { id: 't3', name: 'Jobs & steps', description: 'Define jobs and steps', order: 3, hints: [] },
          { id: 't4', name: 'Secrets', description: 'Use secrets securely', order: 4, hints: [] },
        ],
        learningObjectives: ['Create GitHub Actions', 'Configure triggers', 'Use secrets'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'ci-pipeline' },
      update: {},
      create: {
        slug: 'ci-pipeline',
        name: 'CI Pipeline',
        description: 'Build continuous integration pipelines',
        difficulty: 'EXPERT',
        estimatedHours: 5,
        xpReward: 225,
        treeId: trees.cicd.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Build step', description: 'Automate builds', order: 1, hints: [] },
          { id: 't2', name: 'Test step', description: 'Run automated tests', order: 2, hints: [] },
          { id: 't3', name: 'Lint step', description: 'Add linting', order: 3, hints: [] },
          { id: 't4', name: 'Artifacts', description: 'Save build artifacts', order: 4, hints: [] },
        ],
        learningObjectives: ['Build CI pipelines', 'Automate testing', 'Manage artifacts'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'cd-deployment' },
      update: {},
      create: {
        slug: 'cd-deployment',
        name: 'Continuous Deployment',
        description: 'Automate deployments',
        difficulty: 'MASTER',
        estimatedHours: 6,
        xpReward: 300,
        treeId: trees.cicd.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Deploy staging', description: 'Auto-deploy to staging', order: 1, hints: [] },
          { id: 't2', name: 'Deploy production', description: 'Production deployment', order: 2, hints: [] },
          { id: 't3', name: 'Rollback', description: 'Implement rollback strategy', order: 3, hints: [] },
          { id: 't4', name: 'Blue-green', description: 'Blue-green deployments', order: 4, hints: [] },
        ],
        learningObjectives: ['Automate deployments', 'Implement rollbacks', 'Use deployment strategies'],
        resources: [],
      },
    }),

    // SYSTEM DESIGN TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'scalability-basics' },
      update: {},
      create: {
        slug: 'scalability-basics',
        name: 'Scalability Fundamentals',
        description: 'Design systems that scale',
        difficulty: 'EXPERT',
        estimatedHours: 5,
        xpReward: 225,
        treeId: trees.systemDesign.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Horizontal scaling', description: 'Scale out with more servers', order: 1, hints: [] },
          { id: 't2', name: 'Load balancing', description: 'Distribute traffic', order: 2, hints: [] },
          { id: 't3', name: 'Caching', description: 'Implement caching layers', order: 3, hints: [] },
          { id: 't4', name: 'Database scaling', description: 'Scale databases', order: 4, hints: [] },
        ],
        learningObjectives: ['Design scalable systems', 'Use load balancers', 'Implement caching'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'microservices' },
      update: {},
      create: {
        slug: 'microservices',
        name: 'Microservices Architecture',
        description: 'Design microservices systems',
        difficulty: 'MASTER',
        estimatedHours: 8,
        xpReward: 350,
        treeId: trees.systemDesign.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Service boundaries', description: 'Define service boundaries', order: 1, hints: [] },
          { id: 't2', name: 'Communication', description: 'Choose communication patterns', order: 2, hints: [] },
          { id: 't3', name: 'Data management', description: 'Handle distributed data', order: 3, hints: [] },
          { id: 't4', name: 'Service mesh', description: 'Implement service mesh', order: 4, hints: [] },
        ],
        learningObjectives: ['Design microservices', 'Handle distributed systems', 'Use service mesh'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'design-url-shortener' },
      update: {},
      create: {
        slug: 'design-url-shortener',
        name: 'Design: URL Shortener',
        description: 'Design a scalable URL shortening service',
        difficulty: 'MASTER',
        estimatedHours: 4,
        xpReward: 300,
        treeId: trees.systemDesign.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Requirements', description: 'Define functional requirements', order: 1, hints: [] },
          { id: 't2', name: 'API design', description: 'Design the API', order: 2, hints: [] },
          { id: 't3', name: 'Database schema', description: 'Design data model', order: 3, hints: [] },
          { id: 't4', name: 'Scale considerations', description: 'Plan for scale', order: 4, hints: [] },
        ],
        learningObjectives: ['Gather requirements', 'Design APIs', 'Plan for scale'],
        resources: [],
      },
    }),

    // TYPESCRIPT TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'ts-basics' },
      update: {},
      create: {
        slug: 'ts-basics',
        name: 'TypeScript Basics',
        description: 'Add types to JavaScript',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.typescript.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Setup TS', description: 'Configure TypeScript project', order: 1, hints: [] },
          { id: 't2', name: 'Basic types', description: 'Use primitive types', order: 2, hints: [] },
          { id: 't3', name: 'Arrays & objects', description: 'Type complex structures', order: 3, hints: [] },
          { id: 't4', name: 'Functions', description: 'Type function signatures', order: 4, hints: [] },
        ],
        learningObjectives: ['Setup TypeScript', 'Use basic types', 'Type functions'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'ts-interfaces' },
      update: {},
      create: {
        slug: 'ts-interfaces',
        name: 'Interfaces & Types',
        description: 'Define custom types',
        difficulty: 'JOURNEYMAN',
        estimatedHours: 3,
        xpReward: 150,
        treeId: trees.typescript.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Interfaces', description: 'Define interfaces', order: 1, hints: [] },
          { id: 't2', name: 'Type aliases', description: 'Create type aliases', order: 2, hints: [] },
          { id: 't3', name: 'Union types', description: 'Use union types', order: 3, hints: [] },
          { id: 't4', name: 'Intersection types', description: 'Combine types', order: 4, hints: [] },
        ],
        learningObjectives: ['Create interfaces', 'Use type aliases', 'Combine types'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'ts-generics' },
      update: {},
      create: {
        slug: 'ts-generics',
        name: 'Generics',
        description: 'Write reusable typed code',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.typescript.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Generic functions', description: 'Create generic functions', order: 1, hints: [] },
          { id: 't2', name: 'Generic interfaces', description: 'Define generic interfaces', order: 2, hints: [] },
          { id: 't3', name: 'Constraints', description: 'Add type constraints', order: 3, hints: [] },
          { id: 't4', name: 'Utility types', description: 'Use built-in utilities', order: 4, hints: [] },
        ],
        learningObjectives: ['Write generics', 'Use constraints', 'Apply utility types'],
        resources: [],
      },
    }),

    // AUTHENTICATION TREE QUESTS
    prisma.quest.upsert({
      where: { slug: 'jwt-auth' },
      update: {},
      create: {
        slug: 'jwt-auth',
        name: 'JWT Authentication',
        description: 'Implement token-based auth',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.authentication.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'JWT structure', description: 'Understand JWT format', order: 1, hints: [] },
          { id: 't2', name: 'Generate tokens', description: 'Create access tokens', order: 2, hints: [] },
          { id: 't3', name: 'Verify tokens', description: 'Validate incoming tokens', order: 3, hints: [] },
          { id: 't4', name: 'Refresh tokens', description: 'Implement refresh flow', order: 4, hints: [] },
        ],
        learningObjectives: ['Understand JWTs', 'Generate and verify tokens', 'Handle token refresh'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'oauth-integration' },
      update: {},
      create: {
        slug: 'oauth-integration',
        name: 'OAuth 2.0 Integration',
        description: 'Add social login',
        difficulty: 'EXPERT',
        estimatedHours: 5,
        xpReward: 225,
        treeId: trees.authentication.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'OAuth flow', description: 'Understand OAuth 2.0', order: 1, hints: [] },
          { id: 't2', name: 'Provider setup', description: 'Configure OAuth providers', order: 2, hints: [] },
          { id: 't3', name: 'Callback handling', description: 'Handle OAuth callbacks', order: 3, hints: [] },
          { id: 't4', name: 'User linking', description: 'Link accounts', order: 4, hints: [] },
        ],
        learningObjectives: ['Implement OAuth 2.0', 'Add social providers', 'Handle account linking'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'nextauth-setup' },
      update: {},
      create: {
        slug: 'nextauth-setup',
        name: 'NextAuth.js Setup',
        description: 'Authentication for Next.js',
        difficulty: 'EXPERT',
        estimatedHours: 4,
        xpReward: 200,
        treeId: trees.authentication.id,
        prerequisiteQuestIds: [],
        order: 3,
        tasks: [
          { id: 't1', name: 'Install NextAuth', description: 'Set up NextAuth.js', order: 1, hints: [] },
          { id: 't2', name: 'Providers', description: 'Configure auth providers', order: 2, hints: [] },
          { id: 't3', name: 'Session handling', description: 'Manage user sessions', order: 3, hints: [] },
          { id: 't4', name: 'Protected routes', description: 'Protect pages', order: 4, hints: [] },
        ],
        learningObjectives: ['Set up NextAuth.js', 'Configure providers', 'Protect routes'],
        resources: [],
      },
    }),

    // CAPSTONE QUESTS
    prisma.quest.upsert({
      where: { slug: 'fullstack-capstone-plan' },
      update: {},
      create: {
        slug: 'fullstack-capstone-plan',
        name: 'Capstone: Project Planning',
        description: 'Plan your fullstack capstone project',
        difficulty: 'MASTER',
        estimatedHours: 4,
        xpReward: 250,
        treeId: trees.fullstackProject.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'Define scope', description: 'Define project scope', order: 1, hints: [] },
          { id: 't2', name: 'Choose stack', description: 'Select technology stack', order: 2, hints: [] },
          { id: 't3', name: 'Design database', description: 'Design data models', order: 3, hints: [] },
          { id: 't4', name: 'Create roadmap', description: 'Plan development phases', order: 4, hints: [] },
        ],
        learningObjectives: ['Plan projects', 'Choose technologies', 'Design systems'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'fullstack-capstone-build' },
      update: {},
      create: {
        slug: 'fullstack-capstone-build',
        name: 'Capstone: Build & Deploy',
        description: 'Build and deploy your capstone',
        difficulty: 'MASTER',
        estimatedHours: 40,
        xpReward: 1000,
        treeId: trees.fullstackProject.id,
        prerequisiteQuestIds: [],
        order: 2,
        tasks: [
          { id: 't1', name: 'Build backend', description: 'Implement API and database', order: 1, hints: [] },
          { id: 't2', name: 'Build frontend', description: 'Create user interface', order: 2, hints: [] },
          { id: 't3', name: 'Add auth', description: 'Implement authentication', order: 3, hints: [] },
          { id: 't4', name: 'Deploy', description: 'Deploy to production', order: 4, hints: [] },
          { id: 't5', name: 'Document', description: 'Write documentation', order: 5, hints: [] },
        ],
        learningObjectives: ['Build fullstack apps', 'Deploy applications', 'Write documentation'],
        resources: [],
      },
    }),
    prisma.quest.upsert({
      where: { slug: 'devops-capstone-infra' },
      update: {},
      create: {
        slug: 'devops-capstone-infra',
        name: 'DevOps Capstone: Infrastructure',
        description: 'Build production infrastructure',
        difficulty: 'MASTER',
        estimatedHours: 30,
        xpReward: 800,
        treeId: trees.devopsProject.id,
        prerequisiteQuestIds: [],
        order: 1,
        tasks: [
          { id: 't1', name: 'IaC setup', description: 'Set up infrastructure as code', order: 1, hints: [] },
          { id: 't2', name: 'CI/CD pipeline', description: 'Build complete pipeline', order: 2, hints: [] },
          { id: 't3', name: 'Monitoring', description: 'Add monitoring and alerts', order: 3, hints: [] },
          { id: 't4', name: 'Security', description: 'Implement security measures', order: 4, hints: [] },
        ],
        learningObjectives: ['Build infrastructure', 'Create CI/CD', 'Implement monitoring'],
        resources: [],
      },
    }),
  ])

  console.log(`Created ${quests.length} quests`)

  console.log('Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

